services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend