apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: vaibdan/nginx-reverse-proxy:latest  # Updated to Docker Hub image
        ports:
        - containerPort: 80